#!/bin/bash
#
# /etc/init.d/elfstatsd
#
### BEGIN INIT INFO
# Provides: elfstatsd
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:  3 5
# Default-Stop:   0 1 2 6
# Short-Description: elfstatsd daemon to aggregate web server access stats in ELF format for Munin
# Description:       Runs up the elfstatsd process
### END INIT INFO

if [ -f /etc/sysconfig/elfstatsd ]
    then
        . /etc/sysconfig/elfstatsd
fi

ELFSTATSD_ARGS="-m elfstatsd"

if [ -z "${ELFSTATSD_VIRTUALENV_PATH+x}" ]
    then
        #Virtual environment variable not set, use ELFSTATSD_PATH with default Python
        if [ -z "${ELFSTATSD_PATH+x}" ]
            then
                #Neither ELFSTATSD_VIRTUALENV_PATH nor ELFSTATSD_PATH are set, use standard Python
                true
            else
                ELFSTATSD_ARGS=${ELFSTATSD_PATH}/elfstatsd/__main__.py
        fi
    else
        #Virtual environment variable set, activate environment and use it
        source ${ELFSTATSD_VIRTUALENV_PATH}/bin/activate
fi

case "$1" in
  start)
    # Start the daemon
    python ${ELFSTATSD_ARGS} start
    echo "Elfstatsd started"
    ;;
  stop)
    # Stop the daemon
    python ${ELFSTATSD_ARGS} stop
    echo "Elfstatsd stopped"
    ;;
  restart)
    python ${ELFSTATSD_ARGS} restart
    echo "Elfstatsd restarted"
    ;;
  *)
    # Refuse to do other stuff
    echo "Usage: /etc/init.d/elfstatsd {start|stop|restart}"
    exit 1
    ;;
esac

exit 0