#! /bin/bash
#
# /etc/init.d/elfstatsd
#
### BEGIN INIT INFO
# Provides: elfstatsd
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:  3 5
# Default-Stop:   0 1 2 6
# Short-Description: elfstatsd daemon to aggregate http stats in ELF format for Munin
# Description:       Runs up the elfstatsd process
### END INIT INFO

if [ -z "${ELFSTATSD_VIRTUALENV_PATH+x}" ]
    then
        #Virtual environment variable not set, use standard PYTHON_PATH
        if [ -z "${PYTHONPATH+x}" ]
            then
                echo "Neither ELFSTATSD_VIRTUALENV_PATH nor PYTHONPATH are set, elfstatsd quits"
                exit 1
            else
                DAEMON_PATH=$PYTHONPATH/elfstatsd/elfstatsd.py
        fi
    else
        #Virtual environment variable set, activate environment and use it
        source $ELFSTATSD_VIRTUALENV_PATH/bin/activate
        PYTHON_VERSION=$(python -c'import sys; print "%i.%i" %(sys.version_info[0], sys.version_info[1])')
        DAEMON_PATH=$ELFSTATSD_VIRTUALENV_PATH/lib/python$PYTHON_VERSION/site-packages/elfstatsd/elfstatsd.py
fi

case "$1" in
  start)
    echo "Starting server"
    # Start the daemon
    python $DAEMON_PATH start
    ;;
  stop)
    echo "Stopping server"
    # Stop the daemon
    python $DAEMON_PATH stop
    ;;
  restart)
    echo "Restarting server"
    python $DAEMON_PATH restart
    ;;
  *)
    # Refuse to do other stuff
    echo "Usage: /etc/init.d/elfstatsd {start|stop|restart}"
    exit 1
    ;;
esac

exit 0