#! /bin/bash
#
# /etc/init.d/munindaemon
#
### BEGIN INIT INFO
# Provides: munindaemon
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:  3 5
# Default-Stop:   0 1 2 6
# Short-Description: TomTom munin plugin daemon process
# Description:       Runs up the munindaemon process
### END INIT INFO

VIRTUALENV_PATH='/srv/virtualenvs/munin'
PYTHON_VERSION=$(python -c'import sys; print "%i.%i" %(sys.version_info[0], sys.version_info[1])')
DAEMON_PATH=$VIRTUALENV_PATH/lib/python$PYTHON_VERSION/site-packages/munindaemon/munindaemon.py

#Activate virtualenv
source $VIRTUALENV_PATH/bin/activate

case "$1" in
  start)
    echo "Starting server"
    # Start the daemon
    python $DAEMON_PATH start
    ;;
  stop)
    echo "Stopping server"
    # Stop the daemon
    python $DAEMON_PATH stop
    ;;
  restart)
    echo "Restarting server"
    python $DAEMON_PATH restart
    ;;
  *)
    # Refuse to do other stuff
    echo "Usage: /etc/init.d/munindaemon.sh {start|stop|restart}"
    exit 1
    ;;
esac

exit 0